DROP DATABASE IF EXISTS employee;
CREATE DATABASE employee;

USE employee;

CREATE TABLE department (
  id INT UNASSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  name UNIQUE NOT NULL,
);

CREATE TABLE employees (
  id INT UNASSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
  first_name NOT NULL,
  last_name NOT NULL,
  role_id NOT NULL,
  manager_id UNASSIGNED NOT NULL,
  (id) ON DELETE SET NULL
);

CREATE TABLE role (
    id INT UNASSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
    
)